#!/usr/bin/ruby

if ARGV.length != 1 && ARGV.length != 2
  puts "Usage: #{$0} start_date [end_date]"
  exit 1
end

require 'optparse'
require "open-uri"
require "json"
require "zlib"

PAPERTRAIL_TOKEN = File.read(".token")
PAPERTRAIL_URL   = "https://papertrailapp.com/api/v1/archives.json"

start_date = ARGV[0]
end_date = ARGV[1] || start_date
days = (Date.parse(start_date)..Date.parse(end_date)).map { |date| date.strftime("%Y-%m-%d") }

days.each do |day|
  puts "Processing day: #{day}"
  archives = open(PAPERTRAIL_URL, "X-Papertrail-Token" => PAPERTRAIL_TOKEN) { |f| f.read }

  archives_json = JSON.parse(archives)
  archive       = archives_json.select { |x| x["filename"] == "#{day}.tsv.gz" }

  download_url = archive.first["_links"]["download"]["href"]

  open("log_files/#{day}.tsv", "w") do |local_file|
    open(download_url, "X-Papertrail-Token" => PAPERTRAIL_TOKEN) do |remote_file|
      local_file.write(Zlib::GzipReader.new(remote_file).read)
    end
  end
end

